"use client";

import { useCallback, useEffect, useMemo, useState, useTransition, type FormEvent } from "react";
import {
  cancelFixedAssetDisposalAction,
  createFixedAssetAction,
  deleteFixedAssetAction,
  disposeFixedAssetAction,
  getFixedAssetDataAction,
  updateFixedAssetAction,
  type FixedAssetInput,
} from "@/app/actions";
import type { FixedAsset, FixedAssetDisposal } from "@/db/schema";
import type { DashboardData } from "@/lib/calculations";
import { buildMonthlyDepreciationSchedule, summarizeDepreciationForPeriod } from "@/lib/calculations/depreciation";
import { getFiscalYearBounds } from "@/lib/calculations/fiscal-year";
import { Archive, Download, Pencil, Plus, Search, Trash2, X } from "lucide-react";

type AssetData = Awaited<ReturnType<typeof getFixedAssetDataAction>>;
type SourceType = FixedAssetInput["sourceType"];

interface Props { onDataUpdated?: (data: DashboardData) => void }

interface FormState {
  assetNumber: string; label: string; description: string; category: string; supplierName: string;
  purchaseDate: string; serviceDate: string; invoiceNumber: string; supplierInvoiceId: string; documentUrl: string;
  sourceType: SourceType; sourceTransactionId: string; sourceExpenseItemId: string; sourceIds: string[];
  amountHt: string; vatAmount: string; amountTtc: string; vatRate: string; vatDeductibleRate: string;
  incidentalCosts: string; residualValue: string; durationMonths: string;
  assetAccount: string; depreciationAccount: string; expenseAccount: string;
  isOpeningBalance: boolean; openingDate: string; openingAccumulated: string;
}

const CATEGORIES = [
  ["computer", "Matériel informatique", "36", "2183", "28183", "68112"],
  ["furniture", "Mobilier", "60", "2184", "28184", "68112"],
  ["office", "Matériel de bureau", "60", "2183", "28183", "68112"],
  ["vehicle", "Véhicule", "60", "2182", "28182", "68112"],
  ["software", "Logiciel acquis", "36", "205", "2805", "68111"],
  ["development", "Site / développement immobilisé", "36", "205", "2805", "68111"],
  ["fixtures", "Agencements et installations", "120", "2181", "28181", "68112"],
  ["other", "Autre", "60", "218", "2818", "68112"],
] as const;

const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const today = () => new Date().toISOString().slice(0, 10);
const cents = (value: string) => Math.round((Number.parseFloat(value.replace(",", ".")) || 0) * 100);
const euros = (value: number) => (value / 100).toFixed(2);

function emptyForm(): FormState {
  return { assetNumber: "", label: "", description: "", category: "computer", supplierName: "", purchaseDate: today(), serviceDate: today(), invoiceNumber: "", supplierInvoiceId: "", documentUrl: "", sourceType: "none", sourceTransactionId: "", sourceExpenseItemId: "", sourceIds: [], amountHt: "", vatAmount: "", amountTtc: "", vatRate: "20", vatDeductibleRate: "100", incidentalCosts: "0", residualValue: "0", durationMonths: "36", assetAccount: "2183", depreciationAccount: "28183", expenseAccount: "68112", isOpeningBalance: false, openingDate: today(), openingAccumulated: "0" };
}

function formFromAsset(asset: FixedAsset): FormState {
  return { assetNumber: asset.assetNumber, label: asset.label, description: asset.description ?? "", category: asset.category, supplierName: asset.supplierName, purchaseDate: asset.purchaseDate, serviceDate: asset.serviceDate, invoiceNumber: asset.invoiceNumber ?? "", supplierInvoiceId: asset.supplierInvoiceId ?? "", documentUrl: asset.documentUrl ?? "", sourceType: asset.sourceType as SourceType, sourceTransactionId: asset.sourceTransactionId ?? "", sourceExpenseItemId: asset.sourceExpenseItemId ?? "", sourceIds: [], amountHt: euros(asset.amountHtCents), vatAmount: euros(asset.vatAmountCents), amountTtc: euros(asset.amountTtcCents), vatRate: String(asset.vatRate), vatDeductibleRate: String(asset.vatDeductibleRate), incidentalCosts: euros(asset.incidentalCostsCents), residualValue: euros(asset.residualValueCents), durationMonths: String(asset.depreciationDurationMonths), assetAccount: asset.assetAccount, depreciationAccount: asset.depreciationAccount, expenseAccount: asset.expenseAccount, isOpeningBalance: asset.isOpeningBalance, openingDate: asset.openingDate ?? today(), openingAccumulated: euros(asset.openingAccumulatedDepreciationCents) };
}

export function FixedAssetsSection({ onDataUpdated }: Props) {
  const [isPending, startTransition] = useTransition();
  const [data, setData] = useState<AssetData>({ assets: [], disposals: [], sources: [], transactions: [], expenses: [], supplierInvoices: [], thresholdCents: 50000, fiscalYearEndDay: 31, fiscalYearEndMonth: 12 });
  const [form, setForm] = useState<FormState>(emptyForm);
  const [editing, setEditing] = useState<FixedAsset | null>(null);
  const [modal, setModal] = useState<"asset" | "disposal" | "detail" | null>(null);
  const [selected, setSelected] = useState<FixedAsset | null>(null);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [category, setCategory] = useState("all");
  const [message, setMessage] = useState<string | null>(null);
  const [disposalForm, setDisposalForm] = useState({ type: "sale" as "sale" | "scrap", disposalDate: today(), saleAmountHt: "0", vatRate: "20", notes: "" });

  const availableTransactions = useMemo(() => {
    const used = new Set(data.assets.map((asset) => asset.sourceTransactionId).filter(Boolean));
    return data.transactions.filter((item) => !used.has(item.id) || item.id === editing?.sourceTransactionId);
  }, [data.assets, data.transactions, editing]);
  const availableExpenses = useMemo(() => {
    const used = new Set(data.assets.map((asset) => asset.sourceExpenseItemId).filter(Boolean));
    return data.expenses.filter((item) => !used.has(item.id) || item.id === editing?.sourceExpenseItemId);
  }, [data.assets, data.expenses, editing]);
  const availableSupplierInvoices = useMemo(() => {
    const usedAsSource = new Set(data.assets.filter((asset) => asset.sourceType === "none" && asset.supplierInvoiceId).map((asset) => asset.supplierInvoiceId));
    return data.supplierInvoices.filter((item) => !usedAsSource.has(item.id) || item.id === editing?.supplierInvoiceId);
  }, [data.assets, data.supplierInvoices, editing]);
  const formData = useMemo(() => ({ ...data, transactions: availableTransactions, expenses: availableExpenses, supplierInvoices: availableSupplierInvoices }), [data, availableTransactions, availableExpenses, availableSupplierInvoices]);

  const load = useCallback(() => startTransition(async () => setData(await getFixedAssetDataAction())), []);
  useEffect(() => load(), [load]);

  const bounds = useMemo(() => getFiscalYearBounds(new Date(), data.fiscalYearEndDay, data.fiscalYearEndMonth), [data.fiscalYearEndDay, data.fiscalYearEndMonth]);
  const disposalByAsset = useMemo(() => new Map(data.disposals.map((item) => [item.fixedAssetId, item])), [data.disposals]);
  const summaries = useMemo(() => new Map(data.assets.map((asset) => [asset.id, summarizeDepreciationForPeriod(asset, { startDate: bounds.startDateStr, endDate: bounds.endDateStr }, disposalByAsset.get(asset.id))])), [data.assets, disposalByAsset, bounds]);
  const filtered = useMemo(() => data.assets.filter((asset) => (status === "all" || asset.status === status) && (category === "all" || asset.category === category) && `${asset.assetNumber} ${asset.label} ${asset.supplierName}`.toLowerCase().includes(query.toLowerCase())), [data.assets, status, category, query]);
  const totals = useMemo(() => [...summaries.values()].reduce((sum, item) => ({ depreciation: sum.depreciation + item.depreciationCents, accumulated: sum.accumulated + item.accumulatedDepreciationCents, nbv: sum.nbv + item.closingNetBookValueCents }), { depreciation: 0, accumulated: 0, nbv: 0 }), [summaries]);

  const openCreate = () => { setEditing(null); setForm(emptyForm()); setMessage(null); setModal("asset"); };
  const openEdit = (asset: FixedAsset) => { const sources = data.sources.filter((item) => item.fixedAssetId === asset.id); const base = formFromAsset(asset); const sourceType = (sources[0]?.sourceType ?? asset.sourceType) as SourceType; const sourceIds = sources.map((item) => item.transactionId ?? item.expenseItemId ?? item.supplierInvoiceId).filter((id): id is string => Boolean(id)); setEditing(asset); setForm({ ...base, sourceType, sourceIds, supplierInvoiceId: sourceType === "supplier_invoice" ? sourceIds[0] ?? "" : base.supplierInvoiceId }); setMessage(null); setModal("asset"); };
  const applyCategory = (value: string) => {
    const item = CATEGORIES.find(([id]) => id === value) ?? CATEGORIES.at(-1)!;
    setForm((current) => ({ ...current, category: value, durationMonths: item[2], assetAccount: item[3], depreciationAccount: item[4], expenseAccount: item[5] }));
  };
  const applySource = (type: SourceType, id: string) => {
    if (type === "transaction") {
      const source = data.transactions.find((item) => item.id === id);
      const ttc = source ? Math.abs(source.amount) : 0;
      const ht = ttc / (1 + Number(form.vatRate || 0) / 100);
      setForm((current) => ({ ...current, sourceType: type, sourceTransactionId: id, sourceExpenseItemId: "", label: current.label || source?.label || "", purchaseDate: source?.settledAt.slice(0, 10) || current.purchaseDate, serviceDate: source?.settledAt.slice(0, 10) || current.serviceDate, amountTtc: ttc ? ttc.toFixed(2) : current.amountTtc, amountHt: ttc ? ht.toFixed(2) : current.amountHt, vatAmount: ttc ? (ttc - ht).toFixed(2) : current.vatAmount }));
    } else if (type === "expense_item") {
      const source = data.expenses.find((item) => item.id === id);
      setForm((current) => ({ ...current, sourceType: type, sourceExpenseItemId: id, sourceTransactionId: "", label: current.label || source?.label || "", purchaseDate: source?.date || current.purchaseDate, serviceDate: source?.date || current.serviceDate, amountHt: source ? source.amountHt.toFixed(2) : current.amountHt, vatAmount: source ? source.vatDeductible.toFixed(2) : current.vatAmount, amountTtc: source ? source.reimbursableAmount.toFixed(2) : current.amountTtc, vatRate: source ? String(source.vatRate) : current.vatRate }));
    } else if (type === "supplier_invoice") {
      const source = data.supplierInvoices.find((item) => item.id === id);
      setForm((current) => ({ ...current, sourceType: type, sourceExpenseItemId: "", sourceTransactionId: "", supplierInvoiceId: id, label: current.label || source?.supplierName || "", supplierName: current.supplierName || source?.supplierName || "", invoiceNumber: current.invoiceNumber || source?.invoiceNumber || "", purchaseDate: source?.issueDate || current.purchaseDate, serviceDate: source?.issueDate || current.serviceDate, amountHt: source ? source.totalAmountHt.toFixed(2) : current.amountHt, vatAmount: source ? source.totalVatAmount.toFixed(2) : current.vatAmount, amountTtc: source ? source.totalAmountTtc.toFixed(2) : current.amountTtc }));
    } else setForm((current) => ({ ...current, sourceType: "none", sourceTransactionId: "", sourceExpenseItemId: "" }));
  };
  const applySources = (type: SourceType, ids: string[]) => {
    if (ids.length === 0) return setForm((current) => ({ ...current, sourceType: type, sourceIds: [], sourceTransactionId: "", sourceExpenseItemId: "", supplierInvoiceId: type === "supplier_invoice" ? "" : current.supplierInvoiceId }));
    if (type === "expense_item") {
      const sources = data.expenses.filter((item) => ids.includes(item.id));
      setForm((current) => ({ ...current, sourceType: type, sourceIds: ids, sourceExpenseItemId: ids[0], sourceTransactionId: "", label: current.label || sources[0]?.label || "", purchaseDate: sources.map((item) => item.date).sort()[0] || current.purchaseDate, serviceDate: sources.map((item) => item.date).sort().at(-1) || current.serviceDate, amountHt: sources.reduce((sum,item)=>sum+item.amountHt,0).toFixed(2), vatAmount: sources.reduce((sum,item)=>sum+item.vatDeductible,0).toFixed(2), amountTtc: sources.reduce((sum,item)=>sum+item.reimbursableAmount,0).toFixed(2) }));
    } else if (type === "transaction") {
      const sources = data.transactions.filter((item) => ids.includes(item.id));
      const ttc = sources.reduce((sum,item)=>sum+Math.abs(item.amount),0); const ht = ttc/(1+Number(form.vatRate||0)/100);
      setForm((current) => ({ ...current, sourceType: type, sourceIds: ids, sourceTransactionId: ids[0], sourceExpenseItemId: "", label: current.label || sources[0]?.label || "", purchaseDate: sources.map((item)=>item.settledAt.slice(0,10)).sort()[0] || current.purchaseDate, serviceDate: sources.map((item)=>item.settledAt.slice(0,10)).sort().at(-1) || current.serviceDate, amountHt: ht.toFixed(2), vatAmount: (ttc-ht).toFixed(2), amountTtc: ttc.toFixed(2) }));
    } else if (type === "supplier_invoice") {
      const sources = data.supplierInvoices.filter((item) => ids.includes(item.id));
      setForm((current) => ({ ...current, sourceType: type, sourceIds: ids, supplierInvoiceId: ids[0], sourceTransactionId: "", sourceExpenseItemId: "", supplierName: current.supplierName || sources.map((item)=>item.supplierName).join(", "), label: current.label || sources[0]?.supplierName || "", purchaseDate: sources.map((item)=>item.issueDate).sort()[0] || current.purchaseDate, serviceDate: sources.map((item)=>item.issueDate).sort().at(-1) || current.serviceDate, amountHt: sources.reduce((sum,item)=>sum+item.totalAmountHt,0).toFixed(2), vatAmount: sources.reduce((sum,item)=>sum+item.totalVatAmount,0).toFixed(2), amountTtc: sources.reduce((sum,item)=>sum+item.totalAmountTtc,0).toFixed(2) }));
    }
  };

  const submit = (event: FormEvent) => {
    event.preventDefault(); setMessage(null);
    const input: FixedAssetInput = { assetNumber: form.assetNumber, label: form.label, description: form.description, category: form.category, supplierName: form.supplierName, purchaseDate: form.purchaseDate, serviceDate: form.serviceDate, invoiceNumber: form.invoiceNumber, supplierInvoiceId: form.sourceType === "supplier_invoice" ? form.sourceIds[0] || form.supplierInvoiceId || null : form.supplierInvoiceId || null, documentUrl: form.documentUrl, sourceType: form.sourceType, sourceIds: form.sourceIds, sourceTransactionId: form.sourceTransactionId || null, sourceExpenseItemId: form.sourceExpenseItemId || null, amountHtCents: cents(form.amountHt), vatAmountCents: cents(form.vatAmount), amountTtcCents: cents(form.amountTtc), vatRate: Number(form.vatRate), vatDeductibleRate: Number(form.vatDeductibleRate), incidentalCostsCents: cents(form.incidentalCosts), residualValueCents: cents(form.residualValue), depreciationDurationMonths: Number(form.durationMonths), assetAccount: form.assetAccount, depreciationAccount: form.depreciationAccount, expenseAccount: form.expenseAccount, isOpeningBalance: form.isOpeningBalance, openingDate: form.isOpeningBalance ? form.openingDate : null, openingAccumulatedDepreciationCents: cents(form.openingAccumulated) };
    startTransition(async () => { try { const result = editing ? await updateFixedAssetAction(editing.id, input) : await createFixedAssetAction(input); onDataUpdated?.(result.updatedDashboard); setModal(null); load(); } catch (error) { setMessage((error as Error).message); } });
  };

  const submitDisposal = (event: FormEvent) => { event.preventDefault(); if (!selected) return; const ht = cents(disposalForm.saleAmountHt); const vat = Math.round(ht * Number(disposalForm.vatRate) / 100); startTransition(async () => { try { const result = await disposeFixedAssetAction(selected.id, { type: disposalForm.type, disposalDate: disposalForm.disposalDate, saleAmountHtCents: ht, saleVatAmountCents: vat, saleAmountTtcCents: ht + vat, notes: disposalForm.notes }); onDataUpdated?.(result.updatedDashboard); setModal(null); load(); } catch (error) { setMessage((error as Error).message); } }); };
  const remove = (asset: FixedAsset) => { if (!confirm(`Supprimer définitivement ${asset.assetNumber} — ${asset.label} ?`)) return; startTransition(async () => { const result = await deleteFixedAssetAction(asset.id); onDataUpdated?.(result.updatedDashboard); load(); }); };
  const cancelDisposal = (asset: FixedAsset) => { if (!confirm("Annuler la sortie de cette immobilisation ?")) return; startTransition(async () => { const result = await cancelFixedAssetDisposalAction(asset.id); onDataUpdated?.(result.updatedDashboard); load(); }); };
  const exportCsv = () => downloadCsv("registre_immobilisations.csv", buildRegisterCsv(filtered, summaries));
  const exportPlan = () => downloadCsv("plan_amortissement.csv", buildPlanCsv(filtered, disposalByAsset));

  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">Immobilisations & amortissements</h2><p className="text-sm text-muted-foreground">Registre, dotations et VNC — exercice {bounds.startDateStr} au {bounds.endDateStr}</p></div><div className="flex gap-2"><Button onClick={exportCsv}><Download className="w-4 h-4"/> Registre CSV</Button><Button onClick={exportPlan}><Download className="w-4 h-4"/> Plan CSV</Button><Button primary onClick={openCreate}><Plus className="w-4 h-4"/> Ajouter</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Actifs" value={String(data.assets.filter((item) => item.status === "in_service").length)}/><Kpi label="Dotation de l’exercice" value={euro.format(totals.depreciation / 100)}/><Kpi label="Amortissements cumulés" value={euro.format(totals.accumulated / 100)}/><Kpi label="VNC à la clôture" value={euro.format(totals.nbv / 100)}/></div>
    <div className="rounded-2xl border border-border bg-card p-4"><div className="mb-4 grid gap-3 md:grid-cols-[minmax(18rem,1fr)_13rem_15rem]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 z-10 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input className="input input-search" placeholder="Rechercher numéro, libellé, fournisseur…" value={query} onChange={(event) => setQuery(event.target.value)}/></label><select className="input" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Tous les statuts</option><option value="in_service">En service</option><option value="fully_depreciated">Amorti</option><option value="disposed">Cédé</option><option value="scrapped">Mis au rebut</option></select><select className="input" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Toutes les catégories</option>{CATEGORIES.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></div>
      <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground">{["N°", "Immobilisation", "Mise en service", "Coût", "Durée", "Dotation", "Cumul", "VNC", "Statut", "Actions"].map((item) => <th key={item} className="p-3">{item}</th>)}</tr></thead><tbody>{filtered.map((asset) => { const summary = summaries.get(asset.id)!; return <tr key={asset.id} className="border-b border-border/60"><td className="p-3 font-mono text-xs">{asset.assetNumber}</td><td className="p-3"><button className="font-semibold hover:underline text-left" onClick={() => { setSelected(asset); setModal("detail"); }}>{asset.label}</button><div className="text-xs text-muted-foreground">{categoryLabel(asset.category)} · {asset.supplierName}</div></td><td className="p-3">{asset.serviceDate}</td><td className="p-3">{euro.format(asset.acquisitionCostCents / 100)}</td><td className="p-3">{asset.depreciationDurationMonths} mois</td><td className="p-3">{euro.format(summary.depreciationCents / 100)}</td><td className="p-3">{euro.format(summary.accumulatedDepreciationCents / 100)}</td><td className="p-3 font-semibold">{euro.format(summary.closingNetBookValueCents / 100)}</td><td className="p-3"><span className="rounded-full bg-muted px-2 py-1 text-xs">{statusLabel(asset.status)}</span>{asset.amountHtCents < data.thresholdCents && <div className="mt-1 text-xs text-amber-600">Sous seuil de {euro.format(data.thresholdCents / 100)}</div>}</td><td className="p-3"><div className="flex gap-1"><IconButton label="Modifier" onClick={() => openEdit(asset)}><Pencil/></IconButton>{asset.status === "disposed" || asset.status === "scrapped" ? <IconButton label="Annuler la sortie" onClick={() => cancelDisposal(asset)}><Archive/></IconButton> : <IconButton label="Céder / rebut" onClick={() => { setSelected(asset); setMessage(null); setDisposalForm({ type: "sale", disposalDate: today(), saleAmountHt: "0", vatRate: "20", notes: "" }); setModal("disposal"); }}><Archive/></IconButton>}<IconButton label="Supprimer" danger onClick={() => remove(asset)}><Trash2/></IconButton></div></td></tr>; })}{filtered.length === 0 && <tr><td colSpan={10} className="p-8 text-center text-muted-foreground">Aucune immobilisation.</td></tr>}</tbody></table></div>
    </div>
    {modal === "asset" && <Modal title={editing ? "Modifier l’immobilisation" : "Nouvelle immobilisation"} onClose={() => setModal(null)}><AssetForm form={form} setForm={setForm} data={formData} message={message} isPending={isPending} onCategory={applyCategory} onSource={applySource} onSources={applySources} onSubmit={submit}/></Modal>}
    {modal === "disposal" && selected && <Modal title={`Sortie — ${selected.label}`} onClose={() => setModal(null)}><form onSubmit={submitDisposal} className="space-y-4"><div className="grid grid-cols-2 gap-3"><Field label="Type"><select className="input" value={disposalForm.type} onChange={(e) => setDisposalForm({...disposalForm, type:e.target.value as "sale"|"scrap"})}><option value="sale">Cession</option><option value="scrap">Mise au rebut</option></select></Field><Field label="Date"><input required type="date" className="input" value={disposalForm.disposalDate} onChange={(e) => setDisposalForm({...disposalForm, disposalDate:e.target.value})}/></Field><Field label="Prix HT"><input type="number" min="0" step="0.01" className="input" value={disposalForm.saleAmountHt} onChange={(e) => setDisposalForm({...disposalForm, saleAmountHt:e.target.value})}/></Field><Field label="TVA %"><input type="number" min="0" step="0.1" className="input" value={disposalForm.vatRate} onChange={(e) => setDisposalForm({...disposalForm, vatRate:e.target.value})}/></Field></div><Field label="Notes"><textarea className="input" value={disposalForm.notes} onChange={(e) => setDisposalForm({...disposalForm, notes:e.target.value})}/></Field>{message && <ErrorMessage>{message}</ErrorMessage>}<Submit pending={isPending}/></form></Modal>}
    {modal === "detail" && selected && <Modal title={`${selected.assetNumber} — ${selected.label}`} onClose={() => setModal(null)} wide><AssetDetail asset={selected} disposal={disposalByAsset.get(selected.id)}/></Modal>}
  </div>;
}

function AssetForm({ form, setForm, data, message, isPending, onCategory, onSource, onSources, onSubmit }: { form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>>; data: AssetData; message: string | null; isPending: boolean; onCategory:(v:string)=>void; onSource:(t:SourceType,id:string)=>void; onSources:(t:SourceType,ids:string[])=>void; onSubmit:(e:FormEvent)=>void }) {
  const set = (key: keyof FormState, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  return <form onSubmit={onSubmit} className="space-y-5">
    <Section title="Identification"><div className="grid gap-3 sm:grid-cols-2"><Field label="Numéro (automatique si vide)"><input className="input" value={form.assetNumber} onChange={(e)=>set("assetNumber",e.target.value)}/></Field><Field label="Libellé"><input required className="input" value={form.label} onChange={(e)=>set("label",e.target.value)}/></Field><Field label="Catégorie"><select className="input" value={form.category} onChange={(e)=>onCategory(e.target.value)}>{CATEGORIES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="Fournisseur"><input required className="input" value={form.supplierName} onChange={(e)=>set("supplierName",e.target.value)}/></Field><Field label="Date d’achat"><input required type="date" className="input" value={form.purchaseDate} onChange={(e)=>set("purchaseDate",e.target.value)}/></Field><Field label="Mise en service"><input required type="date" className="input" value={form.serviceDate} onChange={(e)=>set("serviceDate",e.target.value)}/></Field></div></Section>
    <Section title="Source d’achat"><div className="grid gap-3 sm:grid-cols-2"><Field label="Type de source"><select className="input" value={form.sourceType} onChange={(e)=>{ const type=e.target.value as SourceType; setForm((current)=>({...current,sourceType:type,sourceIds:[],sourceTransactionId:"",sourceExpenseItemId:"",supplierInvoiceId:type==="supplier_invoice"?"":current.supplierInvoiceId})); onSource(type,""); }}><option value="none">Aucune / reprise</option><option value="transaction">Transactions Qonto</option><option value="expense_item">Notes de frais</option><option value="supplier_invoice">Factures fournisseur</option></select></Field>{form.sourceType === "transaction" && <MultiSource label="Transactions (Ctrl/Cmd pour plusieurs)" values={form.sourceIds} onChange={(ids)=>onSources("transaction",ids)}>{data.transactions.map((item)=><option key={item.id} value={item.id}>{item.settledAt.slice(0,10)} · {item.label} · {euro.format(Math.abs(item.amount))}</option>)}</MultiSource>}{form.sourceType === "expense_item" && <MultiSource label="Notes de frais (Ctrl/Cmd pour plusieurs)" values={form.sourceIds} onChange={(ids)=>onSources("expense_item",ids)}>{data.expenses.map((item)=><option key={item.id} value={item.id}>{item.date} · {item.label} · {euro.format(item.reimbursableAmount)}</option>)}</MultiSource>}{form.sourceType === "supplier_invoice" ? <MultiSource label="Factures fournisseur (Ctrl/Cmd pour plusieurs)" values={form.sourceIds} onChange={(ids)=>onSources("supplier_invoice",ids)}>{data.supplierInvoices.map((item)=><option key={item.id} value={item.id}>{item.issueDate} · {item.supplierName} · {euro.format(item.totalAmountTtc)}</option>)}</MultiSource> : <Field label="Facture fournisseur (facultative)"><select className="input" value={form.supplierInvoiceId} onChange={(e)=>set("supplierInvoiceId",e.target.value)}><option value="">Aucune</option>{data.supplierInvoices.map((item)=><option key={item.id} value={item.id}>{item.issueDate} · {item.supplierName} · {euro.format(item.totalAmountTtc)}</option>)}</select></Field>}<Field label="N° facture"><input className="input" value={form.invoiceNumber} onChange={(e)=>set("invoiceNumber",e.target.value)}/></Field></div></Section>
    <Section title="Achat et TVA"><div className="grid gap-3 sm:grid-cols-3"><Money label="Montant HT" value={form.amountHt} onChange={(v)=>set("amountHt",v)}/><Money label="TVA" value={form.vatAmount} onChange={(v)=>set("vatAmount",v)}/><Money label="Montant TTC" value={form.amountTtc} onChange={(v)=>set("amountTtc",v)}/><Field label="Taux TVA %"><input type="number" min="0" step="0.1" className="input" value={form.vatRate} onChange={(e)=>set("vatRate",e.target.value)}/></Field><Field label="TVA récupérable %"><input type="number" min="0" max="100" step="0.1" className="input" value={form.vatDeductibleRate} onChange={(e)=>set("vatDeductibleRate",e.target.value)}/></Field><Money label="Frais accessoires" value={form.incidentalCosts} onChange={(v)=>set("incidentalCosts",v)}/></div>{cents(form.amountHt) < data.thresholdCents && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Alerte non bloquante : montant HT inférieur au seuil indicatif de {euro.format(data.thresholdCents/100)}.</p>}</Section>
    <Section title="Amortissement linéaire"><div className="grid gap-3 sm:grid-cols-3"><Field label="Durée (mois)"><input required type="number" min="1" className="input" value={form.durationMonths} onChange={(e)=>set("durationMonths",e.target.value)}/></Field><Money label="Valeur résiduelle" value={form.residualValue} onChange={(v)=>set("residualValue",v)}/><Field label="Compte immobilisation"><input required className="input" value={form.assetAccount} onChange={(e)=>set("assetAccount",e.target.value)}/></Field><Field label="Compte amortissement"><input required className="input" value={form.depreciationAccount} onChange={(e)=>set("depreciationAccount",e.target.value)}/></Field><Field label="Compte dotation"><input required className="input" value={form.expenseAccount} onChange={(e)=>set("expenseAccount",e.target.value)}/></Field></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isOpeningBalance} onChange={(e)=>set("isOpeningBalance",e.target.checked)}/> Reprise d’une immobilisation existante</label>{form.isOpeningBalance && <div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Date de reprise"><input required type="date" className="input" value={form.openingDate} onChange={(e)=>set("openingDate",e.target.value)}/></Field><Money label="Amortissements cumulés repris" value={form.openingAccumulated} onChange={(v)=>set("openingAccumulated",v)}/></div>}</Section>
    <Section title="Informations complémentaires"><Field label="Description / notes"><textarea className="input min-h-20" value={form.description} onChange={(e)=>set("description",e.target.value)}/></Field><Field label="URL du justificatif"><input type="url" className="input" value={form.documentUrl} onChange={(e)=>set("documentUrl",e.target.value)}/></Field></Section>
    {message && <ErrorMessage>{message}</ErrorMessage>}<Submit pending={isPending}/>
  </form>;
}

function AssetDetail({ asset, disposal }: { asset: FixedAsset; disposal?: FixedAssetDisposal }) { const schedule = buildMonthlyDepreciationSchedule(asset, disposal); const sourceLabel = asset.sourceType === "transaction" ? "Transaction" : asset.sourceType === "expense_item" ? "Note de frais" : asset.supplierInvoiceId ? "Facture fournisseur" : "Aucune"; return <div className="space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Kpi label="Coût d’entrée" value={euro.format(asset.acquisitionCostCents/100)}/><Kpi label="Base amortissable" value={euro.format(asset.depreciableBaseCents/100)}/><Kpi label="Valeur résiduelle" value={euro.format(asset.residualValueCents/100)}/><Kpi label="Source" value={sourceLabel}/></div>{disposal && <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{disposal.type === "sale" ? "Cession" : "Mise au rebut"} le {disposal.disposalDate} — résultat indicatif avant fiscalité : {euro.format((disposal.saleAmountHtCents - (schedule.at(-1)?.netBookValueCents ?? asset.acquisitionCostCents))/100)}</p>}<div className="max-h-[50vh] overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-left">Mois</th><th className="p-2 text-right">Dotation</th><th className="p-2 text-right">Cumul</th><th className="p-2 text-right">VNC</th></tr></thead><tbody>{schedule.map((item)=><tr key={item.period} className="border-b border-border/50"><td className="p-2">{item.period}</td><td className="p-2 text-right">{euro.format(item.depreciationCents/100)}</td><td className="p-2 text-right">{euro.format(item.accumulatedDepreciationCents/100)}</td><td className="p-2 text-right">{euro.format(item.netBookValueCents/100)}</td></tr>)}</tbody></table></div></div>; }
function Modal({ title, children, onClose, wide=false }: { title:string; children:React.ReactNode; onClose:()=>void; wide?:boolean }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className={`max-h-[92vh] w-full overflow-auto rounded-2xl bg-background p-6 shadow-xl ${wide?"max-w-5xl":"max-w-3xl"}`}><div className="mb-5 flex items-center justify-between"><h3 className="text-xl font-bold">{title}</h3><button onClick={onClose} aria-label="Fermer"><X/></button></div>{children}</div></div>; }
function Section({ title, children }: {title:string;children:React.ReactNode}) { return <fieldset className="rounded-xl border border-border p-4"><legend className="px-2 font-semibold">{title}</legend>{children}</fieldset>; }
function Field({ label, children }: {label:string;children:React.ReactNode}) { return <label className="block text-sm"><span className="mb-1 block font-medium">{label}</span>{children}</label>; }
function MultiSource({label,values,onChange,children}:{label:string;values:string[];onChange:(ids:string[])=>void;children:React.ReactNode}) { return <Field label={label}><select multiple required size={5} className="input min-h-32" value={values} onChange={(e)=>onChange([...e.currentTarget.selectedOptions].map((option)=>option.value))}>{children}</select></Field>; }
function Money({ label,value,onChange }:{label:string;value:string;onChange:(v:string)=>void}) { return <Field label={label}><input type="number" min="0" step="0.01" className="input" value={value} onChange={(e)=>onChange(e.target.value)}/></Field>; }
function Button({children,onClick,primary=false}:{children:React.ReactNode;onClick:()=>void;primary?:boolean}) { return <button type="button" onClick={onClick} className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold ${primary?"bg-primary text-primary-foreground":"border border-border bg-card hover:bg-muted"}`}>{children}</button>; }
function IconButton({children,label,onClick,danger=false}:{children:React.ReactNode;label:string;onClick:()=>void;danger?:boolean}) { return <button type="button" title={label} aria-label={label} onClick={onClick} className={`rounded-lg p-2 hover:bg-muted [&_svg]:h-4 [&_svg]:w-4 ${danger?"text-red-600":""}`}>{children}</button>; }
function Kpi({label,value}:{label:string;value:string}) { return <div className="rounded-xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>; }
function ErrorMessage({children}:{children:React.ReactNode}) { return <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{children}</p>; }
function Submit({pending}:{pending:boolean}) { return <div className="flex justify-end"><button disabled={pending} className="rounded-xl bg-primary px-5 py-2 font-semibold text-primary-foreground disabled:opacity-50">{pending?"Enregistrement…":"Enregistrer"}</button></div>; }
function categoryLabel(id:string) { return CATEGORIES.find(([value])=>value===id)?.[1] ?? id; }
function statusLabel(value:string) { return ({in_service:"En service",fully_depreciated:"Amorti",disposed:"Cédé",scrapped:"Mis au rebut",draft:"Brouillon"} as Record<string,string>)[value] ?? value; }
function csvCell(value: string | number) { return `"${String(value).replaceAll('"','""')}"`; }
function buildRegisterCsv(assets:FixedAsset[], summaries:Map<string,ReturnType<typeof summarizeDepreciationForPeriod>>) { const lines=[["numero","libelle","categorie","fournisseur","date_achat","mise_en_service","cout_entree","duree_mois","dotation_exercice","cumul","vnc","statut"],...assets.map((asset)=>{const s=summaries.get(asset.id)!;return [asset.assetNumber,asset.label,categoryLabel(asset.category),asset.supplierName,asset.purchaseDate,asset.serviceDate,euros(asset.acquisitionCostCents),asset.depreciationDurationMonths,euros(s.depreciationCents),euros(s.accumulatedDepreciationCents),euros(s.closingNetBookValueCents),statusLabel(asset.status)];})];return lines.map((line)=>line.map(csvCell).join(";")).join("\r\n"); }
function buildPlanCsv(assets:FixedAsset[], disposals:Map<string,FixedAssetDisposal>) { const lines:(string|number)[][]=[["numero","libelle","periode","debut","fin","dotation","cumul","vnc"]]; for(const asset of assets) for(const item of buildMonthlyDepreciationSchedule(asset,disposals.get(asset.id))) lines.push([asset.assetNumber,asset.label,item.period,item.startDate,item.endDate,euros(item.depreciationCents),euros(item.accumulatedDepreciationCents),euros(item.netBookValueCents)]); return lines.map((line)=>line.map(csvCell).join(";")).join("\r\n"); }
function downloadCsv(name:string, content:string) { const url=URL.createObjectURL(new Blob(["\ufeff",content],{type:"text/csv;charset=utf-8"})); const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url); }
